###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
  nu-mysql:
    image: 'mysql:8.0'
    working_dir: /app
    volumes:
      - './data:/app'
    environment:
      - MYSQL_ROOT_PASSWORD=nu_test
      - MYSQL_DATABASE=nu_test
      - MYSQL_USER=nu_test
      - MYSQL_PASSWORD=nu_test
    ports:
      - '8071:3306'

  nu-api-webserver:
    image: 'nginx:alpine'
    working_dir: /app
    volumes:
      - './src:/app'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8070:80'

  nu-api-php:
    build: phpdocker/php-fpm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /app
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      DEBUG: 1
    volumes:
      - './src:/app'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
